baseURL: "https://glistening-kheer-159f89.netlify.app/"
theme: "up-business-theme"
languageCode: "en-us"

title: "MEGA-ACE UNAM"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "MEGA-ACE UNAM"
  description: "Nuestro objetivo es transformar el panorama de la blockchain."
  images: 
    - "images/hero-image.png"

  logo: "logo.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    instagram: "#"
    facebook: "#"
    twitter: "#"

  location:
    - "Facultad de Ingeniería, Av. Universidad 3000, Ciudad Universitaria, Coyoacán, Cd. Mx., CP 04510"

  contact:
    - "algorand@unam.mx"
    - "55 0000 0000"

  copyright: "Copyright © 2023. Departamento de Computación / DIE / Facultad de Ingeniería / UNAM. Todos los Derechos Reservados."

  postProcess: false

menus:
  main:
    - name: "Acerca de"
      url: "/#hero"
      weight: 1

    - name: "Investigación"
      url: "/#"
      weight: 2
      
    - name: "Noticias"
      url: "/#"
      weight: 3

    - name: "Personas/Nuestro equipo"
      url: "/#"
      weight: 4

    - name: "Eventos"
      url: "/#"
      weight: 5

    - name: "Cursos"
      url: "/blog"
      weight: 6

  buttons:
    - name: "Contacto"
      url: "/#"
      weight: 5
      pre: "btn btn-primary text-light"

  footer:
    - name: "Acerca de"
      url: "/#hero"
      weight: 1

    - name: "Investigación"
      url: "/#"
      weight: 2
    
    - name: "Noticias"
      url: "/#"
      weight: 3

    - name: "Personas/Nuestro equipo"
      url: "/#"
      weight: 4

    - name: "Eventos"
      url: "/#"
      weight: 5

    - name: "Cursos"
      url: "/blog"
      weight: 6

taxonomies:
  series: "series"
  tags: "tags"
