baseURL: "https://63966daece2690765c36166e--glistening-kheer-159f89.netlify.app/"
theme: "up-business-theme"
languageCode: "en-us"

title: "MEGA-ACE UNAM"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "MEGA-ACE UNAM"
  description: "Nuestro objetivo es transformar el panorama de la blockchain."
  images: 
    - "images/hero-image.png"

  logo: "ACE.svg"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    dribbble: "#"
    instagram: "#"
    facebook: "#"
    twitter: "#"

  location:
    - "3891 Ranchview Dr. Richardson, California 62639"
    - "4517 Washington Ave. Manchester, Kentucky 39495"

  contact:
    - "trungkienspktnd@gamail.com"
    - "207.555.0119"

  copyright: "Copyright © 2023. Departamento de Computación / DIE / Facultad de Ingeniería / UNAM. Todos los Derechos Reservados."

  postProcess: false

menus:
  main:
    - name: "Acerca de"
      url: "/#hero"
      weight: 1

    - name: "Investigación"
      url: "/#"
      weight: 2
      
    - name: "Noticias"
      url: "/#"
      weight: 3

    - name: "Personas/Nuestro equipo"
      url: "/#"
      weight: 4

    - name: "Eventos"
      url: "/#"
      weight: 5

    - name: "Cursos"
      url: "/blog"
      weight: 6

  buttons:
    - name: "Contacto"
      url: "/#"
      weight: 5
      pre: "btn btn-primary text-light"

  footer:
    - name: "Acerca de"
      url: "/#hero"
      weight: 1

    - name: "Investigación"
      url: "/#"
      weight: 2
    
    - name: "Noticias"
      url: "/#"
      weight: 3

    - name: "Personas/Nuestro equipo"
      url: "/#"
      weight: 4

    - name: "Eventos"
      url: "/#"
      weight: 5

    - name: "Cursos"
      url: "/blog"
      weight: 6

taxonomies:
  series: "series"
  tags: "tags"
