name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: "Deploy to server"
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy site
        run: sshpass -v -p "${{ secrets.SSH_PASSWORD }}" ssh "${{ secrets.SSH_USER }}@${{ secrets.SSH_IP }}" 'cd ${{ secrets.PROJECT_ROOT }} && git clone ${{ secrets.PROJECT_REPO_URL }} && cd mega-ace-unam && hugo --gc --buildFuture && cp -r public/** .. && cd .. && rm -rf mega-ace-unam'